name: pfas_gnn_env
channels:
  - pyg
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly     
  - pyg
  - numpy             
  - pip
  - pip:
      - networkx
      - matplotlib
      - pandas