name: pfas_gnn_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip>=23.2
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - tqdm
  - rdkit
  - jupyterlab
  - ipykernel
  - pyarrow        # optional but nice for parquet datasets
  - pyyaml
  - networkx
  - ase            # useful if you later handle structures
  - pymatgen       # useful for CIF/materials workflows