name: pfas-ml
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - networkx
  - rdkit
  - jupyterlab
  - ipykernel
  - pyyaml
